### PR TITLE
fix: only works for single paths, so rename argument

### PR DESCRIPTION
**Pull request by dword-design**

### CODE REVIEW

**Comment by ridvanaltun** [comment]
LGTM 🎉

**Comment by dword-design** [comment]
@ridvanaltun Thanks for merging. Addition: I haven't changed the variable names because I haven't found tests. I guess they can also be changed.

**Comment by ridvanaltun** [comment]
> @ridvanaltun Thanks for merging. Addition: I haven't changed the variable names because I haven't found tests. I guess they can also be changed.

I changed the variables already, see ridvanaltun/dropbox-ignore-anywhere@59161a2

**Pull request merged**
